apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: danieltabiri@yahoo.co.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: danieltabiri@yahoo.co.uk
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key

        # - or -
        # API Token:
        #   apiTokenSecretRef:
        #     name: cloudflare-api-token-secret
        #     key: api-token        
      # (Optional) Add DNS selectors
      # ---
      # selector:
      #   dnsZones:
      #   - 'your-domain'

    # HTTP Challenge:
    # - http01:
    #    ingress:
    #      class: traefik
